# Site settings
title: Newman
baseurl: "/newman"
safe: true
lsi: false
highlighter: rouge
#email: newman@soteradefense.com
website: http://www.soteradefense.com
description: > # this means to ignore newlines until "baseurl:"
    "When you control the mail, you control... information"

url: "http://sotera.github.io"
github_username:  Sotera
repository_url: https://github.com/Sotera/newman

show_downloads: true
zip_url: https://github.com/Sotera/newman/zipball/master
tar_url: https://github.com/Sotera/newman/tarball/master

theme: jekyll-theme-hacker